### ISSUE TITLE
Is it possible to change the opacity of blur?

### ISSUE THREAD

**Issue by kinokn** [riverar/sample-win32-acrylicblur#1]
I want to create an adjustable win32 acrylic. Users can choose from transparent to acrylic and intermediate state.
For example, opacity="0" stands for completely transparent, everything in the background get through, while opacity="1" is the current view.
Adding opacity on window doesn't work well :(

**Comment by riverar** [comment]
@KIRI-Z Try 0.50 for 50%. 😄
