### ISSUE TITLE
DragMove is laggy

### ISSUE THREAD

**Issue by MythreyaK** [riverar/sample-win32-acrylicblur#4]
While trying to drag and move the window around, the movement lags a lot. I've also enabled resizing; resizing windows also causes laggy behavior. I also tried this with a C++ app (but with some glitches, as shown in this [SO answer](https://stackoverflow.com/a/41433592/8560442). 

~Note the blur going off to the bottom and to the right~
![image](https://user-images.githubusercontent.com/26112391/68582502-e7e45200-04a0-11ea-8ab4-87003bf9aac8.png)

I was wondering if you could shed some light on the issue. 
Thanks!

Update: I was able to fix the blur 'exceeding bounds' by setting the AccentFlags, but the laggy window dragging and resizing issue remains.

**Comment by dkonik** [comment]
Duplicate of #2

**Comment by MythreyaK** [comment]
Whoops, my bad! Closing this then.
